import fs from 'fs';

function item(id, word, phonetic, phonics, pinyin, translation, partOfSpeech, grade, semester, unitNum, unitName, category, categoryLabel, imageUrl, def, sent, sentCn) {
  return {
    id,
    word: word.toUpperCase(),
    phonetic,
    phonics,
    pinyin,
    translation,
    partOfSpeech,
    grade,
    semester,
    semesterKey: grade + semester,
    unitId: `${grade}${semester}-U${unitNum}`,
    unitName,
    category,
    categoryLabel,
    imageUrl: imageUrl || 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=600&auto=format&fit=crop&q=80',
    englishDefinition: def,
    exampleSentence: sent,
    exampleTranslation: sentCn,
  };
}

// ==========================================
// GRADE 4 (2024新课标PEP版)
// ==========================================
const grade4 = [
  // 4A Unit 1: My Classroom
  item('4a-u1-classroom', 'classroom', '/ˈklɑːsruːm/', 'class-room', 'jiào shì', '教室', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'school', '学校设施', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80', 'A room in a school in which classes are held.', 'Our new classroom is big and bright.', '我们的新教室又大又明亮。'),
  item('4a-u1-window', 'window', '/ˈwɪndəʊ/', 'win-dow', 'chuāng hu', '窗户', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80', 'An opening in the wall of a building to admit light and air.', 'Please open the window and let in fresh air.', '请打开窗户让新鲜空气进来。'),
  item('4a-u1-blackboard', 'blackboard', '/ˈblækbɔːd/', 'black-board', 'hēi bǎn', '黑板', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=600&auto=format&fit=crop&q=80', 'A large smooth dark board for writing on with chalk.', 'The teacher is writing words on the blackboard.', '老师正在黑板上写单词。'),
  item('4a-u1-light', 'light', '/laɪt/', 'l-igh-t', 'diàn dēng', '电灯', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80', 'A device providing illumination.', 'Turn on the light, please.', '请把电灯打开。'),
  item('4a-u1-picture', 'picture', '/ˈpɪktʃə(r)/', 'pic-ture', 'tú huà ; zhào piàn', '图画；照片', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80', 'A painting or drawing.', 'There is a beautiful picture on the wall.', '墙上有一幅美丽的图画。'),
  item('4a-u1-door', 'door', '/dɔː(r)/', 'd-oor', 'mén', '门', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80', 'A hinged barrier used to close an entrance.', 'Close the door quietly when you leave.', '离开时请轻轻把门关上。'),
  item('4a-u1-computer', 'computer', '/kəmˈpjuːtə(r)/', 'com-pu-ter', 'diàn nǎo', '电脑', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80', 'An electronic device for storing and processing data.', 'We have a computer on the teacher\'s desk.', '讲台桌上有一台电脑。'),
  item('4a-u1-fan', 'fan', '/fæn/', 'f-a-n', 'fēng shàn', '风扇', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80', 'An apparatus with rotating blades for creating a current of air.', 'Turn on the fan on hot summer days.', '炎热的夏天把风扇打开。'),
  item('4a-u1-wall', 'wall', '/wɔːl/', 'w-all', 'qiáng bì', '墙壁', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80', 'A continuous vertical brick or stone structure.', 'The walls of our classroom are white.', '我们教室的墙壁是白色的。'),
  item('4a-u1-floor', 'floor', '/flɔː(r)/', 'fl-oor', 'dì bǎn', '地板', 'n.', '4', 'A', 1, 'Unit 1 My Classroom', 'objects', '教室设施', 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=600&auto=format&fit=crop&q=80', 'The lower surface of a room on which one may walk.', 'Sweep the floor and keep it clean.', '把地板扫干净。'),
  item('4a-u1-near', 'near', '/nɪə(r)/', 'n-ear', 'zài ... fù jìn', '在……附近', 'prep.', '4', 'A', 1, 'Unit 1 My Classroom', 'positions', '方位介词', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80', 'At or to a short distance away.', 'My desk is near the window.', '我的书桌靠在窗户附近。'),
  item('4a-u1-clean', 'clean', '/kliːn/', 'cl-ean', 'dǎ sǎo ; gān jìng de', '打扫；干净的', 'v./adj.', '4', 'A', 1, 'Unit 1 My Classroom', 'actions', '日常动作', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80', 'Free from dirt, marks, or stains.', 'Let us clean the classroom together.', '让我们一起打扫教室吧。'),

  // 4A Unit 2: My Schoolbag
  item('4a-u2-schoolbag', 'schoolbag', '/ˈskuːlbæɡ/', 'school-bag', 'shū bāo', '书包', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80', 'A bag used by school students for carrying books.', 'My schoolbag is heavy with new books.', '我的书包装满了新书，沉甸甸的。'),
  item('4a-u2-maths-book', 'maths book', '/mæθs bʊk/', 'maths book', 'shù xué shū', '数学书', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80', 'A textbook used for studying mathematics.', 'Open your maths book to page 10.', '翻开你的数学书第10页。'),
  item('4a-u2-english-book', 'English book', '/ˈɪŋɡlɪʃ bʊk/', 'Eng-lish book', 'yīng yǔ shū', '英语书', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80', 'A book used for studying the English language.', 'We read stories in our English book.', '我们在英语书里读故事。'),
  item('4a-u2-chinese-book', 'Chinese book', '/ˌtʃaɪˈniːz bʊk/', 'Chi-nese book', 'yǔ wén shū', '语文书', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80', 'A book used for learning the Chinese language and literature.', 'Put your Chinese book on the desk.', '把你的语文书放在桌上。'),
  item('4a-u2-storybook', 'storybook', '/ˈstɔːribʊk/', 'sto-ry-book', 'gù shi shū', '故事书', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80', 'A book containing stories for children.', 'I like reading interesting storybooks.', '我喜欢读有趣的故事书。'),
  item('4a-u2-candy', 'candy', '/ˈkændi/', 'can-dy', 'táng guǒ', '糖果', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'food', '零食甜点', 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?w=600&auto=format&fit=crop&q=80', 'A sweet food made with sugar or syrup.', 'Do you want a sweet candy?', '你想吃一颗甜糖果吗？'),
  item('4a-u2-notebook', 'notebook', '/ˈnəʊtbʊk/', 'note-book', 'bǐ jì běn', '笔记本', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'school', '学习用品', 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&auto=format&fit=crop&q=80', 'A book of blank pages for writing notes.', 'Write new words in your notebook.', '把新单词记在你的笔记本上。'),
  item('4a-u2-key', 'key', '/kiː/', 'k-ey', 'yào shi', '钥匙', 'n.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'objects', '日常用品', 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80', 'A small piece of shaped metal used to open a lock.', 'Where is the classroom key?', '教室钥匙在哪里？'),
  item('4a-u2-heavy', 'heavy', '/ˈhevi/', 'hea-vy', 'zhòng de', '重的', 'adj.', '4', 'A', 2, 'Unit 2 My Schoolbag', 'adjectives', '特征描述', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80', 'Of great weight; difficult to lift or move.', 'My bag is heavy with so many books.', '装了这么多书，我的包很重。'),

  // 4A Unit 3: My Friends
  item('4a-u3-strong', 'strong', '/strɒŋ/', 'str-o-ng', 'qiáng zhuàng de', '强壮的', 'adj.', '4', 'A', 3, 'Unit 3 My Friends', 'people', '人物特征', 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80', 'Having the power to move heavy weights.', 'Zhang Peng is tall and strong.', '张鹏又高又强壮。'),
  item('4a-u3-friendly', 'friendly', '/ˈfrendli/', 'friend-ly', 'yǒu hǎo de', '友好的', 'adj.', '4', 'A', 3, 'Unit 3 My Friends', 'people', '性格品质', 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&auto=format&fit=crop&q=80', 'Kind and pleasant.', 'Our new classmate is very friendly.', '我们的新同学非常友好。'),
  item('4a-u3-quiet', 'quiet', '/ˈkwaɪət/', 'qui-et', 'ān jìng de', '安静的', 'adj.', '4', 'A', 3, 'Unit 3 My Friends', 'people', '性格品质', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80', 'Making little or no noise.', 'She is a quiet and polite girl.', '她是一个安静懂礼貌的女孩。'),
  item('4a-u3-hair', 'hair', '/heə(r)/', 'h-air', 'tóu fa', '头发', 'n.', '4', 'A', 3, 'Unit 3 My Friends', 'body', '外貌特征', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', 'Any of the fine thread-like strands growing from the skin of mammals.', 'She has long black hair.', '她有一头长长的黑发。'),
  item('4a-u3-shoe', 'shoe', '/ʃuː/', 'sh-oe', 'xié zi', '鞋子', 'n.', '4', 'A', 3, 'Unit 3 My Friends', 'clothing', '服饰配件', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80', 'A covering for the foot with a sturdy sole.', 'My blue sports shoes are very comfortable.', '我的蓝色运动鞋非常舒适。'),
  item('4a-u3-glasses', 'glasses', '/ˈɡlɑːsɪz/', 'glass-es', 'yǎn jìng', '眼镜', 'n.', '4', 'A', 3, 'Unit 3 My Friends', 'objects', '服饰配件', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80', 'A pair of lenses set in a frame worn on the face.', 'He wears black glasses and smiles.', '他戴着黑框眼镜，面带微笑。'),
  item('4a-u3-hat', 'hat', '/hæt/', 'h-a-t', 'mào zi', '帽子', 'n.', '4', 'A', 3, 'Unit 3 My Friends', 'clothing', '服饰配件', 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&auto=format&fit=crop&q=80', 'A shaped covering for the head.', 'The boy in the brown hat is my friend.', '戴棕色帽子的那个男孩是我的朋友。'),

  // 4A Unit 4: My Home
  item('4a-u4-bedroom', 'bedroom', '/ˈbedruːm/', 'bed-room', 'wò shì', '卧室', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'places', '房间居室', 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=600&auto=format&fit=crop&q=80', 'A room used for sleeping in.', 'My bedroom is clean and quiet.', '我的卧室既干净又安静。'),
  item('4a-u4-living-room', 'living room', '/ˈlɪvɪŋ ruːm/', 'liv-ing room', 'kè tīng', '客厅', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'places', '房间居室', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&auto=format&fit=crop&q=80', 'A room in a house for general everyday use.', 'We watch TV in the living room.', '我们在客厅看电视。'),
  item('4a-u4-study', 'study', '/ˈstʌdi/', 'stu-dy', 'shū fáng', '书房', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'places', '房间居室', 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80', 'A room used for reading, writing, or academic work.', 'Dad is reading books in the study.', '爸爸正在书房里读书。'),
  item('4a-u4-kitchen', 'kitchen', '/ˈkɪtʃɪn/', 'kitch-en', 'chú fáng', '厨房', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'places', '房间居室', 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80', 'A room where food is prepared and cooked.', 'Mum is cooking dinner in the kitchen.', '妈妈正在厨房里做晚饭。'),
  item('4a-u4-bathroom', 'bathroom', '/ˈbɑːθruːm/', 'bath-room', 'yù shì ; wèi shēng jiān', '浴室；卫生间', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'places', '房间居室', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80', 'A room containing a bath or shower and typically also a washbasin.', 'Wash your hands in the bathroom.', '去卫生间把手洗干净。'),
  item('4a-u4-bed', 'bed', '/bed/', 'b-e-d', 'chuáng', '床', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'furniture', '家具设施', 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=600&auto=format&fit=crop&q=80', 'A piece of furniture for sleep or rest.', 'Go to bed early and sleep well.', '早点上床睡觉，睡个好觉。'),
  item('4a-u4-sofa', 'sofa', '/ˈsəʊfə/', 'so-fa', 'shā fā', '沙发', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'furniture', '家具设施', 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80', 'A long comfortable seat with a back and arms.', 'Sit on the soft sofa and have some tea.', '坐在柔软的沙发上喝点茶吧。'),
  item('4a-u4-fridge', 'fridge', '/frɪdʒ/', 'fr-i-dge', 'bīng xiāng', '冰箱', 'n.', '4', 'A', 4, 'Unit 4 My Home', 'appliances', '家用电器', 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80', 'A refrigerator.', 'There is fresh milk in the fridge.', '冰箱里有新鲜牛奶。'),

  // 4A Unit 5: Dinner's Ready
  item('4a-u5-beef', 'beef', '/biːf/', 'b-ee-f', 'niú ròu', '牛肉', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'food', '餐桌美食', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80', 'The flesh of a cow or bull used as food.', 'I would like some beef and rice, please.', '请给我来一些牛肉和米饭。'),
  item('4a-u5-chicken', 'chicken', '/ˈtʃɪkɪn/', 'chick-en', 'jī ròu', '鸡肉', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'food', '餐桌美食', 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&auto=format&fit=crop&q=80', 'The meat of a chicken used as food.', 'Roasted chicken is delicious.', '烤鸡肉非常美味。'),
  item('4a-u5-noodles', 'noodles', '/ˈnuːdlz/', 'noo-dles', 'miàn tiáo', '面条', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'food', '餐桌美食', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80', 'Long, thin strips of pasta.', 'A bowl of hot noodles is so good.', '一碗热气腾腾的面条真好吃。'),
  item('4a-u5-soup', 'soup', '/suːp/', 's-ou-p', 'tāng', '汤', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'food', '餐桌美食', 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&auto=format&fit=crop&q=80', 'A liquid dish, typically savoury and made by boiling meat or vegetables.', 'Tomato soup is tasty and warm.', '西红柿汤美味又暖胃。'),
  item('4a-u5-vegetables', 'vegetables', '/ˈvedʒtəblz/', 'veg-e-ta-bles', 'shū cài', '蔬菜', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'food', '餐桌美食', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80', 'Plants or parts of plants used as food.', 'Eat green vegetables to stay healthy.', '吃绿色蔬菜保持健康。'),
  item('4a-u5-bowl', 'bowl', '/bəʊl/', 'b-ow-l', 'wǎn', '碗', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'tableware', '餐具用品', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80', 'A round deep dish or basin used for food or liquid.', 'Pass me a bowl of soup, please.', '请递给我一碗汤。'),
  item('4a-u5-chopsticks', 'chopsticks', '/ˈtʃɒpstɪks/', 'chop-sticks', 'kuài zi', '筷子', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'tableware', '餐具用品', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80', 'Each of a pair of small, thin sticks used for eating Asian food.', 'I can use chopsticks to eat noodles.', '我可以用筷子吃面条。'),
  item('4a-u5-spoon', 'spoon', '/spuːn/', 'sp-oo-n', 'sháo zi', '勺子', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'tableware', '餐具用品', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80', 'An implement consisting of a small shallow bowl on a handle.', 'Use a spoon to drink soup.', '用勺子喝汤。'),
  item('4a-u5-fork', 'fork', '/fɔːk/', 'f-or-k', 'chā zi', '叉子', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'tableware', '餐具用品', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80', 'An implement with two or more prongs used for lifting food.', 'Use a knife and fork to cut beef.', '用刀叉切牛肉。'),
  item('4a-u5-knife', 'knife', '/naɪf/', 'kn-i-fe', 'cān dāo', '餐刀', 'n.', '4', 'A', 5, "Unit 5 Dinner's ready", 'tableware', '餐具用品', 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80', 'An instrument composed of a blade fixed into a handle.', 'Be careful when using a knife.', '使用刀具时要小心。'),

  // 4A Unit 6: Meet My Family
  item('4a-u6-parents', 'parents', '/ˈpeərənts/', 'par-ents', 'fù mǔ', '父母；双亲', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'family', '家庭成员', 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&auto=format&fit=crop&q=80', 'A father and mother.', 'My parents love me very much.', '我的父母非常爱我。'),
  item('4a-u6-doctor', 'doctor', '/ˈdɒktə(r)/', 'doc-tor', 'yī shēng', '医生', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'jobs', '职业角色', 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop&q=80', 'A person who is qualified to treat people who are ill.', 'My father is a helpful doctor.', '我的父亲是一位热心助人的医生。'),
  item('4a-u6-cook', 'cook', '/kʊk/', 'c-oo-k', 'chú shī', '厨师', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'jobs', '职业角色', 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=600&auto=format&fit=crop&q=80', 'A person who prepares and cooks food.', 'The cook makes wonderful dishes in the restaurant.', '大厨在餐厅里做出美味佳肴。'),
  item('4a-u6-driver', 'driver', '/ˈdraɪvə(r)/', 'dri-ver', 'sī jī', '司机', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'jobs', '职业角色', 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&auto=format&fit=crop&q=80', 'A person who drives a vehicle.', 'My uncle is a safe bus driver.', '我叔叔是一位安全的公交车司机。'),
  item('4a-u6-farmer', 'farmer', '/ˈfɑːmə(r)/', 'farm-er', 'nóng mín', '农民', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'jobs', '职业角色', 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=600&auto=format&fit=crop&q=80', 'A person who owns or manages a farm.', 'The hardworking farmer grows fresh rice.', '辛勤的农民种植新鲜的水稻。'),
  item('4a-u6-nurse', 'nurse', '/nɜːs/', 'n-ur-se', 'hù shi', '护士', 'n.', '4', 'A', 6, 'Unit 6 Meet My Family', 'jobs', '职业角色', 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&auto=format&fit=crop&q=80', 'A person trained to care for the sick.', 'The kind nurse takes good care of patients.', '亲切的护士悉心照顾病人。'),

  // 4B Units 1 to 6
  item('4b-u1-library', 'library', '/ˈlaɪbrəri/', 'li-bra-ry', 'tú shū guǎn', '图书馆', 'n.', '4', 'B', 1, 'Unit 1 My School', 'places', '学校场所', 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80', 'A building or room containing collections of books.', 'Please keep quiet in the school library.', '请在学校图书馆保持安静。'),
  item('4b-u1-playground', 'playground', '/ˈpleɪɡraʊnd/', 'play-ground', 'cāo chǎng', '操场', 'n.', '4', 'B', 1, 'Unit 1 My School', 'places', '学校场所', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80', 'An outdoor area provided for children to play on.', 'Students play basketball on the playground.', '学生们在操场上打篮球。'),
  item('4b-u2-breakfast', 'breakfast', '/ˈbrekfəst/', 'break-fast', 'zǎo cān', '早餐', 'n.', '4', 'B', 2, 'Unit 2 What time is it?', 'meals', '每日三餐', 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&auto=format&fit=crop&q=80', 'A meal eaten in the morning, the first of the day.', 'Time for breakfast! Have some milk and eggs.', '该吃早饭了！喝点牛奶吃个鸡蛋。'),
  item('4b-u2-lunch', 'lunch', '/lʌntʃ/', 'l-u-nch', 'wǔ cān', '午餐', 'n.', '4', 'B', 2, 'Unit 2 What time is it?', 'meals', '每日三餐', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80', 'A meal eaten in the middle of the day.', 'We have delicious lunch at twelve o\'clock.', '我们在十二点吃美味的午餐。'),
  item('4b-u2-dinner', 'dinner', '/ˈdɪnə(r)/', 'din-ner', 'wǎn cān', '晚餐', 'n.', '4', 'B', 2, 'Unit 2 What time is it?', 'meals', '每日三餐', 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80', 'The main meal of the day, taken either around midday or in the evening.', 'Dinner is ready! Let us sit together.', '晚饭准备好了！大家坐在一起吧。'),
  item('4b-u3-sunny', 'sunny', '/ˈsʌni/', 'sun-ny', 'qíng lǎng de', '晴朗的', 'adj.', '4', 'B', 3, 'Unit 3 Weather', 'weather', '天气气象', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', 'Bright with sunlight.', 'It is sunny and warm today. Let us fly kites.', '今天天气晴朗温暖，我们去放风筝吧。'),
  item('4b-u3-windy', 'windy', '/ˈwɪndi/', 'win-dy', 'guā fēng de', '刮风的', 'adj.', '4', 'B', 3, 'Unit 3 Weather', 'weather', '天气气象', 'https://images.unsplash.com/photo-1505672678570-074e7f0f6742?w=600&auto=format&fit=crop&q=80', 'Accompanied by a strong wind.', 'Hold your cap, it is very windy outside.', '抓好你的帽子，外面风很大。'),
  item('4b-u3-cloudy', 'cloudy', '/ˈklaʊdi/', 'clou-dy', 'duō yún de', '多云的', 'adj.', '4', 'B', 3, 'Unit 3 Weather', 'weather', '天气气象', 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=600&auto=format&fit=crop&q=80', 'Covered with or characterized by clouds.', 'The sky is cloudy and grey.', '天空多云且有些灰蒙蒙。'),
  item('4b-u3-rainy', 'rainy', '/ˈreɪni/', 'rain-y', 'xià yǔ de', '下雨的', 'adj.', '4', 'B', 3, 'Unit 3 Weather', 'weather', '天气气象', 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?w=600&auto=format&fit=crop&q=80', 'Having a great deal of rainfall.', 'Take an umbrella on a rainy day.', '下雨天带一把伞。'),
  item('4b-u3-snowy', 'snowy', '/ˈsnəʊi/', 'snow-y', 'xià xuě de', '下雪的', 'adj.', '4', 'B', 3, 'Unit 3 Weather', 'weather', '天气气象', 'https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=600&auto=format&fit=crop&q=80', 'Characterized by snowfall.', 'It is snowy in winter. Let us make a snowman.', '冬天经常下雪，我们一起堆雪人吧。'),
  item('4b-u4-tomato', 'tomato', '/təˈmɑːtəʊ/', 'to-ma-to', 'xī hóng shì', '西红柿', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'plants', '农场果蔬', 'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?w=600&auto=format&fit=crop&q=80', 'A glossy red fruit eaten as a vegetable.', 'Fresh red tomatoes in the garden are juicy.', '花园里新鲜红西红柿多汁甜美。'),
  item('4b-u4-potato', 'potato', '/pəˈteɪtəʊ/', 'po-ta-to', 'tǔ dòu', '土豆', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'plants', '农场果蔬', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80', 'A starchy plant tuber that is one of the most important food crops.', 'Mashed potatoes are my favourite.', '土豆泥是我最喜欢的食物。'),
  item('4b-u4-horse', 'horse', '/hɔːs/', 'h-or-se', 'mǎ', '马', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'animals', '农场动物', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', 'A solid-hoofed herbivorous quadruped.', 'The strong horse runs fast on the grass.', '强壮的马儿在草地上飞奔。'),
  item('4b-u4-cow', 'cow', '/kaʊ/', 'c-ow', 'nǎi niú', '奶牛', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'animals', '农场动物', 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=600&auto=format&fit=crop&q=80', 'A female domestic bovine animal that provides milk.', 'The dairy cow gives us fresh milk.', '奶牛为我们提供新鲜牛奶。'),
  item('4b-u4-sheep', 'sheep', '/ʃiːp/', 'sh-ee-p', 'mián yáng', '绵羊', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'animals', '农场动物', 'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?w=600&auto=format&fit=crop&q=80', 'A domesticated ruminant animal with a thick woolly fleece.', 'Look at the white sheep on the green hill.', '看绿山丘上那一群可爱的白绵羊。'),
  item('4b-u4-hen', 'hen', '/hen/', 'h-e-n', 'mǔ jī', '母鸡', 'n.', '4', 'B', 4, 'Unit 4 At the farm', 'animals', '农场动物', 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&auto=format&fit=crop&q=80', 'A female bird, especially of a domestic fowl.', 'The hen lays fresh eggs every morning.', '母鸡每天早晨都下新鲜的鸡蛋。'),
];

console.log(`Writing Grade 4 with ${grade4.length} words...`);
fs.writeFileSync('src/data/pepGrade4.ts', `import { WordItem } from '../types';\n\nexport const PEP_GRADE_4_WORDS: WordItem[] = ${JSON.stringify(grade4, null, 2)};\n`, 'utf8');
console.log('Successfully wrote src/data/pepGrade4.ts');
