import fs from 'fs';
import path from 'path';

console.log('Generating PEP vocabulary dataset with 2024 revised curriculum & natural phonics...');

// ==================== GRADE 3 ====================
const grade3Words = [
  // 3A Unit 1: Making Friends (2024新版)
  {
    id: '3a-u1-ear',
    word: 'EAR',
    phonetic: '/ɪə(r)/',
    phonics: 'ear',
    pinyin: 'ěr duo',
    translation: '耳朵',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The organ of hearing on each side of the head.',
    exampleSentence: 'Touch your ear and listen to the teacher.',
    exampleTranslation: '摸摸你的耳朵，仔细听老师讲。',
  },
  {
    id: '3a-u1-eye',
    word: 'EYE',
    phonetic: '/aɪ/',
    phonics: 'eye',
    pinyin: 'yǎn jing',
    translation: '眼睛',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The organ of sight in humans and animals.',
    exampleSentence: 'Look at the book with your bright eyes.',
    exampleTranslation: '用你明亮的眼睛看这本书。',
  },
  {
    id: '3a-u1-mouth',
    word: 'MOUTH',
    phonetic: '/maʊθ/',
    phonics: 'm-ou-th',
    pinyin: 'zuǐ',
    translation: '嘴',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1588731234159-8b9963143fca?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The opening through which food is taken in and sounds are emitted.',
    exampleSentence: 'Open your mouth and smile happily.',
    exampleTranslation: '张开嘴巴，开心微笑。',
  },
  {
    id: '3a-u1-nose',
    word: 'NOSE',
    phonetic: '/nəʊz/',
    phonics: 'n-o-se',
    pinyin: 'bí zi',
    translation: '鼻子',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The part projecting above the mouth on the face used for smelling and breathing.',
    exampleSentence: 'Touch your nose and say hello.',
    exampleTranslation: '摸摸你的鼻子，然后说你好。',
  },
  {
    id: '3a-u1-arm',
    word: 'ARM',
    phonetic: '/ɑːm/',
    phonics: 'ar-m',
    pinyin: 'gē bo',
    translation: '胳膊',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Either of the two upper limbs of the human body.',
    exampleSentence: 'Wave your arm to say goodbye.',
    exampleTranslation: '挥动你的胳膊说再见。',
  },
  {
    id: '3a-u1-hand',
    word: 'HAND',
    phonetic: '/hænd/',
    phonics: 'h-a-n-d (短元音 a)',
    pinyin: 'shǒu',
    translation: '手',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The end part of a person\'s arm beyond the wrist.',
    exampleSentence: 'Clap your hands and make friends!',
    exampleTranslation: '拍拍你的双手，一起交朋友！',
  },
  {
    id: '3a-u1-leg',
    word: 'LEG',
    phonetic: '/leɡ/',
    phonics: 'l-e-g',
    pinyin: 'tuǐ',
    translation: '腿',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Each of the limbs on which a person or animal walks and stands.',
    exampleSentence: 'Shake your legs and jump up!',
    exampleTranslation: '晃动双腿，跳起来吧！',
  },
  {
    id: '3a-u1-foot',
    word: 'FOOT',
    phonetic: '/fʊt/',
    phonics: 'f-oo-t',
    pinyin: 'jiǎo',
    translation: '脚',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'body',
    categoryLabel: '身体部位',
    imageUrl: 'https://images.unsplash.com/photo-1519415943484-9fa1873496d4?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The lower extremity of the leg below the ankle.',
    exampleSentence: 'Stamp your foot on the floor.',
    exampleTranslation: '在地上跺一跺你的脚。',
  },
  {
    id: '3a-u1-friend',
    word: 'FRIEND',
    phonetic: '/frend/',
    phonics: 'fr-ie-nd',
    pinyin: 'péng you',
    translation: '朋友',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A person you know and like very much.',
    exampleSentence: 'We can play together and be good friends.',
    exampleTranslation: '我们可以一起玩，成为好朋友。',
  },
  {
    id: '3a-u1-help',
    word: 'HELP',
    phonetic: '/help/',
    phonics: 'h-e-l-p',
    pinyin: 'bāng zhù',
    translation: '帮助',
    partOfSpeech: 'v.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'actions',
    categoryLabel: '交友动作',
    imageUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'To make it easier for someone to do something.',
    exampleSentence: 'I can help you carry the books.',
    exampleTranslation: '我可以帮你拿书。',
  },
  {
    id: '3a-u1-share',
    word: 'SHARE',
    phonetic: '/ʃeə(r)/',
    phonics: 'sh-are',
    pinyin: 'fēn xiǎng',
    translation: '分享',
    partOfSpeech: 'v.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'actions',
    categoryLabel: '交友动作',
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'To give a portion of something to another person.',
    exampleSentence: 'We share our toys and pencils.',
    exampleTranslation: '我们分享玩具和铅笔。',
  },
  {
    id: '3a-u1-smile',
    word: 'SMILE',
    phonetic: '/smaɪl/',
    phonics: 'sm-i-le',
    pinyin: 'wēi xiào',
    translation: '微笑',
    partOfSpeech: 'v./n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'actions',
    categoryLabel: '交友动作',
    imageUrl: 'https://images.unsplash.com/photo-1544717302-de2939b7ef71?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A pleased or kind facial expression.',
    exampleSentence: 'Give your new classmate a big smile.',
    exampleTranslation: '给你的新同学一个灿烂的微笑。',
  },
  {
    id: '3a-u1-listen',
    word: 'LISTEN',
    phonetic: '/ˈlɪsn/',
    phonics: 'l-i-s-ten',
    pinyin: 'tīng',
    translation: '听；倾听',
    partOfSpeech: 'v.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'actions',
    categoryLabel: '交友动作',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'To give one\'s attention to a sound.',
    exampleSentence: 'Listen carefully with your ears.',
    exampleTranslation: '用你的耳朵仔细倾听。',
  },
  {
    id: '3a-u1-say',
    word: 'SAY',
    phonetic: '/seɪ/',
    phonics: 's-ay',
    pinyin: 'shuō',
    translation: '说；讲',
    partOfSpeech: 'v.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'actions',
    categoryLabel: '交友动作',
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'To utter words so as to convey information.',
    exampleSentence: 'Say hello to your new friend.',
    exampleTranslation: '向你的新朋友说声你好。',
  },
  {
    id: '3a-u1-name',
    word: 'NAME',
    phonetic: '/neɪm/',
    phonics: 'n-a-me',
    pinyin: 'míng zi',
    translation: '名字',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A word by which a person is known.',
    exampleSentence: 'What is your name? My name is Wu Binbin.',
    exampleTranslation: '你叫什么名字？我叫吴斌斌。',
  },
  {
    id: '3a-u1-nice',
    word: 'NICE',
    phonetic: '/naɪs/',
    phonics: 'n-i-ce',
    pinyin: 'lìng rén yú kuài de',
    translation: '令人愉快的；友好的',
    partOfSpeech: 'adj.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Pleasant, agreeable, or kind.',
    exampleSentence: 'Nice to meet you, Mike!',
    exampleTranslation: '见到你很高兴，麦克！',
  },
  {
    id: '3a-u1-can',
    word: 'CAN',
    phonetic: '/kæn/',
    phonics: 'c-a-n',
    pinyin: 'néng ; kě yǐ',
    translation: '能；可以',
    partOfSpeech: 'modal v.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Be able to do something.',
    exampleSentence: 'We can share and play together.',
    exampleTranslation: '我们可以一起分享和玩耍。',
  },
  {
    id: '3a-u1-goodbye',
    word: 'GOODBYE',
    phonetic: '/ˌɡʊdˈbaɪ/',
    phonics: 'good-bye',
    pinyin: 'zài jiàn',
    translation: '再见',
    partOfSpeech: 'interj.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Used on parting or at the end of a conversation.',
    exampleSentence: 'Goodbye, see you tomorrow!',
    exampleTranslation: '再见，明天见！',
  },
  {
    id: '3a-u1-toy',
    word: 'TOY',
    phonetic: '/tɔɪ/',
    phonics: 't-oy',
    pinyin: 'wán jù',
    translation: '玩具',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 1,
    unitName: 'Unit 1 Making Friends',
    category: 'daily',
    categoryLabel: '日常交友',
    imageUrl: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'An object for a child to play with.',
    exampleSentence: 'This toy bear is so cute.',
    exampleTranslation: '这个玩具熊真可爱。',
  },

  // 3A Unit 2: Different Families
  {
    id: '3a-u2-family',
    word: 'FAMILY',
    phonetic: '/ˈfæməli/',
    phonics: 'fam-i-ly',
    pinyin: 'jiā tíng',
    translation: '家；家庭',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A group consisting of parents and children living together.',
    exampleSentence: 'I love my big and warm family.',
    exampleTranslation: '我爱我庞大而温暖的家庭。',
  },
  {
    id: '3a-u2-father',
    word: 'FATHER',
    phonetic: '/ˈfɑːðə(r)/',
    phonics: 'fa-ther',
    pinyin: 'fù qīn',
    translation: '父亲；爸爸',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A male parent.',
    exampleSentence: 'My father is tall and kind.',
    exampleTranslation: '我的父亲高大而且和蔼。',
  },
  {
    id: '3a-u2-dad',
    word: 'DAD',
    phonetic: '/dæd/',
    phonics: 'd-a-d',
    pinyin: 'bà ba',
    translation: '（口语）爸爸',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Informal word for father.',
    exampleSentence: 'Dad, can we go to the park?',
    exampleTranslation: '爸爸，我们可以去公园吗？',
  },
  {
    id: '3a-u2-mother',
    word: 'MOTHER',
    phonetic: '/ˈmʌðə(r)/',
    phonics: 'mo-ther',
    pinyin: 'mǔ qīn',
    translation: '母亲；妈妈',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A female parent.',
    exampleSentence: 'My mother reads storybooks to me.',
    exampleTranslation: '妈妈给我读故事书。',
  },
  {
    id: '3a-u2-mum',
    word: 'MUM',
    phonetic: '/mʌm/',
    phonics: 'm-u-m',
    pinyin: 'mā ma',
    translation: '（口语）妈妈',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Informal word for mother.',
    exampleSentence: 'Mum is making delicious noodles.',
    exampleTranslation: '妈妈正在做美味的面条。',
  },
  {
    id: '3a-u2-grandpa',
    word: 'GRANDPA',
    phonetic: '/ˈɡrænpɑː/',
    phonics: 'grand-pa',
    pinyin: 'yé ye ; lǎo ye',
    translation: '爷爷；姥爷',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Informal word for grandfather.',
    exampleSentence: 'Grandpa tells funny stories.',
    exampleTranslation: '爷爷讲有趣的故事。',
  },
  {
    id: '3a-u2-grandma',
    word: 'GRANDMA',
    phonetic: '/ˈɡrænmɑː/',
    phonics: 'grand-ma',
    pinyin: 'nǎi nai ; lǎo lao',
    translation: '奶奶；姥姥',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Informal word for grandmother.',
    exampleSentence: 'Grandma plants sweet flowers.',
    exampleTranslation: '奶奶种植了芳香的花朵。',
  },
  {
    id: '3a-u2-grandfather',
    word: 'GRANDFATHER',
    phonetic: '/ˈɡrænfɑːðə(r)/',
    phonics: 'grand-fa-ther',
    pinyin: 'zǔ fù ; wài zǔ fù',
    translation: '（外）祖父',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The father of one\'s father or mother.',
    exampleSentence: 'My grandfather likes tea.',
    exampleTranslation: '我的祖父喜欢喝茶。',
  },
  {
    id: '3a-u2-grandmother',
    word: 'GRANDMOTHER',
    phonetic: '/ˈɡrænmʌðə(r)/',
    phonics: 'grand-mo-ther',
    pinyin: 'zǔ mǔ ; wài zǔ mǔ',
    translation: '（外）祖母',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The mother of one\'s father or mother.',
    exampleSentence: 'My grandmother is very kind.',
    exampleTranslation: '我的祖母非常慈祥。',
  },
  {
    id: '3a-u2-brother',
    word: 'BROTHER',
    phonetic: '/ˈbrʌðə(r)/',
    phonics: 'bro-ther',
    pinyin: 'gē ge ; dì di',
    translation: '兄；弟',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A male sibling.',
    exampleSentence: 'My brother likes playing soccer.',
    exampleTranslation: '我的哥哥喜欢踢足球。',
  },
  {
    id: '3a-u2-sister',
    word: 'SISTER',
    phonetic: '/ˈsɪstə(r)/',
    phonics: 'sis-ter',
    pinyin: 'jiě jie ; mèi mei',
    translation: '姐；妹',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A female sibling.',
    exampleSentence: 'My sister is a good student.',
    exampleTranslation: '我的妹妹是个好学生。',
  },
  {
    id: '3a-u2-cousin',
    word: 'COUSIN',
    phonetic: '/ˈkʌzn/',
    phonics: 'cou-sin',
    pinyin: 'táng xiōng dì jiě mèi',
    translation: '堂（表）兄弟；堂（表）姐妹',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A child of one\'s uncle or aunt.',
    exampleSentence: 'My cousin is five years old.',
    exampleTranslation: '我的表弟五岁了。',
  },
  {
    id: '3a-u2-uncle',
    word: 'UNCLE',
    phonetic: '/ˈʌŋkl/',
    phonics: 'un-cle',
    pinyin: 'shū shu ; jiù jiu',
    translation: '伯父；叔父；舅父；姑父；姨父',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The brother of one\'s father or mother.',
    exampleSentence: 'My uncle has a big farm.',
    exampleTranslation: '我叔叔有一个大农场。',
  },
  {
    id: '3a-u2-aunt',
    word: 'AUNT',
    phonetic: '/ɑːnt/',
    phonics: 'au-nt',
    pinyin: 'gū mu ; yí mu',
    translation: '伯母；婶母；舅母；姑母；姨母',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'The sister of one\'s father or mother.',
    exampleSentence: 'My aunt is an English teacher.',
    exampleTranslation: '我的姑姑是一位英语老师。',
  },
  {
    id: '3a-u2-baby',
    word: 'BABY',
    phonetic: '/ˈbeɪbi/',
    phonics: 'ba-by',
    pinyin: 'yīng ér',
    translation: '婴儿',
    partOfSpeech: 'n.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'family',
    categoryLabel: '家庭成员',
    imageUrl: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'A very young child.',
    exampleSentence: 'The baby has small hands.',
    exampleTranslation: '这个婴儿有一双小手。',
  },
  {
    id: '3a-u2-have',
    word: 'HAVE',
    phonetic: '/hæv/',
    phonics: 'h-a-ve',
    pinyin: 'yǒu',
    translation: '有',
    partOfSpeech: 'v.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'verbs',
    categoryLabel: '动作与状态',
    imageUrl: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Possess, own, or hold.',
    exampleSentence: 'I have a big family.',
    exampleTranslation: '我有一个大家庭。',
  },
  {
    id: '3a-u2-big',
    word: 'BIG',
    phonetic: '/bɪɡ/',
    phonics: 'b-i-g',
    pinyin: 'dà de',
    translation: '大的',
    partOfSpeech: 'adj.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'adjectives',
    categoryLabel: '特征描述',
    imageUrl: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Of considerable size or extent.',
    exampleSentence: 'We live in a big house.',
    exampleTranslation: '我们住在一栋大房子里。',
  },
  {
    id: '3a-u2-small',
    word: 'SMALL',
    phonetic: '/smɔːl/',
    phonics: 'sm-all',
    pinyin: 'xiǎo de',
    translation: '小的',
    partOfSpeech: 'adj.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'adjectives',
    categoryLabel: '特征描述',
    imageUrl: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Of a size that is less than normal.',
    exampleSentence: 'This is a small puppy.',
    exampleTranslation: '这是一只小幼犬。',
  },
  {
    id: '3a-u2-some',
    word: 'SOME',
    phonetic: '/sʌm/',
    phonics: 's-o-me',
    pinyin: 'yī xiē',
    translation: '一些',
    partOfSpeech: 'det./pron.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'adjectives',
    categoryLabel: '特征描述',
    imageUrl: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'An unspecified amount or number of.',
    exampleSentence: 'Here are some photos of my family.',
    exampleTranslation: '这里有一些我家人的照片。',
  },
  {
    id: '3a-u2-me',
    word: 'ME',
    phonetic: '/miː/',
    phonics: 'm-e',
    pinyin: 'wǒ',
    translation: '我',
    partOfSpeech: 'pron.',
    grade: '3',
    semester: 'A',
    unit: 2,
    unitName: 'Unit 2 Different Families',
    category: 'pronouns',
    categoryLabel: '人称代词',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    englishDefinition: 'Used by a speaker to refer to himself or herself as the object.',
    exampleSentence: 'This is me in the photo!',
    exampleTranslation: '照片里这个人就是我！',
  },
];

console.log(`Loaded ${grade3Words.length} base words for Grade 3A.`);
